"use client";
import { useState } from "react";
import type { PlanAssignment, PlanBusyEntry } from "./monthly-plan-rules";
type P={id:string;name:string;active:boolean}; type S={id:string;personId:string;date:string;activity:string;workMinutes:number;segments:{aircraft:string;flightMinutes:number;nightMinutes:number}[]}; type A={id:string;title:string;detail:string;sortDate:string;severity:"danger"|"warning"};
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; const start=()=>`${new Date().getFullYear()}-${String(new Date().getMonth()+1).padStart(2,"0")}-01`; const fmt=(m:number)=>`${Math.floor(m/60)}:${String(m%60).padStart(2,"0")}`;
export function AnalyticsView({people,shifts,assignments,busyEntries,alerts,onNavigate}:{people:P[];shifts:S[];assignments:PlanAssignment[];busyEntries:PlanBusyEntry[];alerts:A[];onNavigate:(v:"documentation"|"shifts"|"training"|"planning"|"actual")=>void}){
 const[from,setFrom]=useState(start);const[to,setTo]=useState(()=>iso(new Date()));const period=shifts.filter(x=>x.date>=from&&x.date<=to);const flights=period.filter(x=>x.activity==="flight");const plan=assignments.filter(x=>x.date>=from&&x.date<=to);const done=plan.filter(a=>flights.some(s=>s.personId===a.personId&&s.date===a.date&&s.segments.some(g=>g.aircraft===a.aircraft)));const training=period.filter(x=>["periodic_training","ground_training"].includes(x.activity)).length+busyEntries.filter(x=>x.activity==="periodic_training"&&x.dateFrom<=to&&x.dateTo>=from).length;const warnings=alerts.filter(x=>!x.sortDate||(x.sortDate>=from&&x.sortDate<=to));const rows=people.filter(x=>x.active).map(person=>{const own=period.filter(x=>x.personId===person.id);return{person,shifts:own.filter(x=>x.activity==="flight").length,work:own.reduce((n,x)=>n+x.workMinutes,0),flight:own.flatMap(x=>x.segments).reduce((n,x)=>n+x.flightMinutes,0),night:own.flatMap(x=>x.segments).reduce((n,x)=>n+x.nightMinutes,0)}}).sort((a,b)=>b.flight-a.flight||a.person.name.localeCompare(b.person.name,"ru-RU"));const total=rows.reduce((n,x)=>n+x.flight,0);const percent=plan.length?Math.round(done.length/plan.length*100):0;
 return <section className="analytics-view"><div className="panel analytics-heading"><div><p className="eyebrow">Документация и аналитика</p><h2>Управленческая сводка</h2></div><div className="analytics-period"><label>С <input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>По <input type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></label></div></div><div className="analytics-metrics"><article><span>Налёт</span><strong>{fmt(total)}</strong><small>за период</small></article><article><span>Полётные смены</span><strong>{flights.length}</strong><small>факт</small></article><article><span>План выполнен</span><strong>{percent}%</strong><small>{done.length} из {plan.length}</small></article><article><span>Подготовка</span><strong>{training}</strong><small>записей</small></article><article className={warnings.length?"danger":"good"}><span>Требует внимания</span><strong>{warnings.length}</strong><small>сроки и нарушения</small></article></div><div className="analytics-grid"><article className="panel analytics-workload"><header><div><p className="eyebrow">Загрузка пилотов</p><h3>Рабочее и полётное время</h3></div><button onClick={()=>onNavigate("shifts")}>Журнал и отчёты →</button></header><div className="table-scroll"><table><thead><tr><th>Сотрудник</th><th>Смены</th><th>Рабочее</th><th>Налёт</th><th>Ночь</th></tr></thead><tbody>{rows.map(x=><tr key={x.person.id}><td>{x.person.name}</td><td>{x.shifts}</td><td>{fmt(x.work)}</td><td><strong>{fmt(x.flight)}</strong></td><td>{fmt(x.night)}</td></tr>)}</tbody></table></div></article><div className="analytics-side"><article className="panel"><p className="eyebrow">План / факт</p><h3>{done.length} выполнено · {Math.max(0,plan.length-done.length)} без факта</h3><div className="analytics-progress"><i style={{width:`${percent}%`}}/></div><button onClick={()=>onNavigate("planning")}>Месячный план</button><button onClick={()=>onNavigate("actual")}>Фактический план</button></article><article className="panel"><p className="eyebrow">Быстрые действия</p><button onClick={()=>onNavigate("documentation")}>Формы и реестр документов</button><button onClick={()=>onNavigate("training")}>Матрица подготовки</button><button onClick={()=>onNavigate("shifts")}>Сформировать отчёт</button></article></div></div></section>;
}
