"use client";
type ImportKind = "backup" | "worktime" | "aviabit" | "flightbook";
const sources: { kind: ImportKind; title: string; format: string; detail: string; checks: string[] }[] = [
  { kind: "backup", title: "Резервная база", format: "JSON · BaseShtab", detail: "Полное восстановление сотрудников, смен, планов, личных дел и настроек.", checks: ["структура файла", "контрольная сумма", "совместимость версии"] },
  { kind: "worktime", title: "Рабочее время", format: "Excel · Авиабит", detail: "Полётные смены, налёт, ночь, типы ВС, борта, примечания и разделение смен.", checks: ["сопоставление сотрудников", "спорные кресла", "дубликаты и ошибки"] },
  { kind: "aviabit", title: "Документы и сроки", format: "Excel · Авиабит", detail: "Сертификация, свидетельства, подготовка и сроки действия в личном деле.", checks: ["сотрудник", "даты и тип ВС", "предварительный просмотр"] },
  { kind: "flightbook", title: "Исходный налёт", format: "Excel · ЭЛК", detail: "Контрольная точка лётной книжки с проверкой налёта по типам и креслам.", checks: ["итоги по типам", "КВС / инструктор / 2-й пилот", "ночной налёт"] },
];
export function ImportCenterView({ counts, onStart }: { counts: { people: number; shifts: number; documents: number; baselines: number }; onStart: (kind: ImportKind) => void }) {
  return <section className="import-center"><div className="panel import-center-intro"><div><p className="eyebrow">Безопасная загрузка данных</p><h2>Единый центр импорта</h2><p>Выберите источник. Данные сохраняются только после проверки и подтверждения. Перед записью сайт создаёт точку восстановления.</p></div><div className="import-current-state"><span>Сотрудников <strong>{counts.people}</strong></span><span>Смен <strong>{counts.shifts}</strong></span><span>Документов <strong>{counts.documents}</strong></span><span>Точек налёта <strong>{counts.baselines}</strong></span></div></div><div className="import-source-grid">{sources.map((source) => <article className="panel import-source-card" key={source.kind}><header><div><strong>{source.title}</strong><span>{source.format}</span></div><i>Импорт</i></header><p>{source.detail}</p><ul>{source.checks.map((item) => <li key={item}>✓ {item}</li>)}</ul><button className="primary-button" onClick={() => onStart(source.kind)}>Выбрать файл</button></article>)}</div><div className="panel import-safety"><strong>Порядок:</strong><span>1. Чтение</span><span>2. Сверка</span><span>3. Предпросмотр</span><span>4. Подтверждение</span><span>5. Запись с отменой</span></div></section>;
}
